/*
 * ULTRASONIC_SENSOR_priv.h
 *
 *  Created on: Jul 7, 2023
 *      Author: fathy
 */

#ifndef HAL_ULTRASONIC_SENSOR_ULTRASONIC_SENSOR_PRIV_H_
#define HAL_ULTRASONIC_SENSOR_ULTRASONIC_SENSOR_PRIV_H_



#endif /* HAL_ULTRASONIC_SENSOR_ULTRASONIC_SENSOR_PRIV_H_ */
