/*
 * ULTRASONIC_SENSOR_conf.h
 *
 *  Created on: Jul 7, 2023
 *      Author: fathy
 */

#ifndef HAL_ULTRASONIC_SENSOR_ULTRASONIC_SENSOR_CONF_H_
#define HAL_ULTRASONIC_SENSOR_ULTRASONIC_SENSOR_CONF_H_

#define ULTRASONIC_SENSOR_TRIG_GROUP    DIO_u8GROUP_C
#define ULTRASONIC_SENSOR_TRIG_PIN      DIO_u8PIN0

#define ULTRASONIC_SENSOR_ECHO_GROUP    DIO_u8GROUP_D
#define ULTRASONIC_SENSOR_ECHO_PIN      DIO_u8PIN2

#endif /* HAL_ULTRASONIC_SENSOR_ULTRASONIC_SENSOR_CONF_H_ */
