/*
 * ICU_int.h
 *
 *  Created on: Jul 9, 2023
 *      Author: fathy
 */

#ifndef MCAL_ICU_ICU_INT_H_
#define MCAL_ICU_ICU_INT_H_

/*******************************************************************************
 *                         Types Declaration                                   *
 *******************************************************************************/
typedef enum
{
	NO_CLOCK,F_1,F_8,F_64,F_256,F_1024
}Icu_Clock;

typedef enum
{
	FALLING_EDGE,RISING_EDGE
}Icu_EdgeType;

typedef struct
{
	Icu_Clock clock;
	Icu_EdgeType edge;
}Icu_ConfigType;

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/
/*
 * Description : Function to initialize the ICU driver
 * 	1. Set the required clock.
 * 	2. Set the required edge detection.
 * 	3. Enable the Input Capture Interrupt.
 * 	4. Initialize Timer1 Registers
 */
void Icu_voidInit(const Icu_ConfigType * Config_Ptr);

/*
 * Description: Function to set the Call Back function address.
 */
void Icu_voidSetCallBack(void(*a_ptr)(void));

/*
 * Description: Function to set the required edge detection.
 */
void Icu_voidSetEdgeDetectionType(const Icu_EdgeType edgeType);

/*
 * Description: Function to get the Timer1 Value when the input is captured
 *              The value stored at Input Capture Register ICR1
 */
u16 Icu_u16GetInputCaptureValue(void);

/*
 * Description: Function to clear the Timer1 Value to start count from ZERO
 */
void Icu_voidClearTimerValue(void);

/*
 * Description: Function to disable the Timer1 to stop the ICU Driver
 */
void Icu_voidDeInit(void);


void ULTRASONIC_SENSOR_voidInit(void);

/*
 * Description:
 * 1. Send the Trigger pulse to the ultrasonic.
 */
void ULTRASONIC_SENSOR_voidTrigger(void);

/*
 * Description:
 * 1. Send the trigger pulse by using Ultrasonic_Trigger function.
 * 2. Start the measurements by the ICU from this moment.
 * 3. return the measured distance in Centimeter.
 */
u16 ULTRASONIC_SENSOR_u16ReadDistance(void);

/*
 * Description:
 * 1. This is the call back function called by the ICU driver.
 * 2. This is used to calculate the high time (pulse time) generated by
 *    the ultrasonic sensor.
 */
void ULTRASONIC_SENSOR_voidEdgeProcessing(void);


#endif /* MCAL_ICU_ICU_INT_H_ */
